{"status":"FAIL","msg":"FAIL:\n Uncaught: { name: \"Test262Error\", message: \"Expected a ReferenceError to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/language/expressions/assignment/assignment-operator-calls-putvalue-lref--rval-.js:26\n    at ../../test262/test/language/expressions/assignment/assignment-operator-calls-putvalue-lref--rval-.js:24\n\n","path":"../../test262/test/language/expressions/assignment/assignment-operator-calls-putvalue-lref--rval-.js","memory_kb":0,"duration":325311071}