{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Array.from(itemsPoisonedSymbolIterator) throws a Test262Error exception Expected a Function but got a TypeError\" }\n    at ../../test262/harness/assert.js:95\n    at anonymous (../../test262/test/built-ins/Array/from/iter-get-iter-err.js:20)\n\n","path":"../../test262/test/built-ins/Array/from/iter-get-iter-err.js"}