{"status":"FAIL","msg":"FAIL:\n Uncaught: [object Object]\n    at test262/harness/assert.js:71\n    at anonymous (test262/test/built-ins/String/prototype/trimEnd/this-value-object-valueof-call-err.js:50)\n\n","path":"test262/test/built-ins/String/prototype/trimEnd/this-value-object-valueof-call-err.js"}