{"status":"FAIL","msg":"FAIL:\n Uncaught: { name: \"Test262Error\", message: \"Expected a Test262Error to be thrown but no exception was thrown at all (Testing with BigInt64Array.)\" }\n    at ../../test262/harness/testBigIntTypedArray.js:37\n    at testWithBigIntTypedArrayConstructors (../../test262/test/built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-tostring.js:48)\n\n","path":"../../test262/test/built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-tostring.js","memory_kb":0,"duration":274672373}