{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a TypeError to be thrown but no exception was thrown at all\", name: \"Test262Error\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/annexB/built-ins/escape/to-primitive-err.js:20\n\n","path":"../../test262/test/annexB/built-ins/escape/to-primitive-err.js","memory_kb":0,"duration":151024325}