{"status":"FAIL","msg":"FAIL:\n ReferenceError: Cannot call next on 1\n    at Function (../../test262/test/language/statements/class/elements/after-same-line-gen-rs-static-generator-method-privatename-identifier-alt.js:117)\n\n","path":"../../test262/test/language/statements/class/elements/after-same-line-gen-rs-static-generator-method-privatename-identifier-alt.js","memory_kb":0,"duration":179806725}