{"status":"FAIL","msg":"FAIL:\n Uncaught: { name: \"Test262Error\", message: \"Expected a TypeError to be thrown but no exception was thrown at all\" }\n    at ../../test262/harness/assert.js:101\n    at ../../test262/test/built-ins/String/raw/nextkey-is-symbol-throws.js:28\n\n","path":"../../test262/test/built-ins/String/raw/nextkey-is-symbol-throws.js","memory_kb":0,"duration":280981133}