{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"obj should have an own property cause\", name: \"Test262Error\" }\n    at ../../test262/harness/assert.js:18\n    at assert (../../test262/harness/propertyHelper.js:63)\n    at verifyProperty (../../test262/test/built-ins/AggregateError/cause-property.js:31)\n\n","path":"../../test262/test/built-ins/AggregateError/cause-property.js","memory_kb":0,"duration":49331985}