{"status":"FAIL","msg":"FAIL:\n Uncaught: { message: \"Expected a Function but got a TypeError\" }\n    at ../../test262/harness/assert.js:95\n    at anonymous (../../test262/test/built-ins/Array/prototype/includes/return-abrupt-tointeger-fromindex.js:25)\n\n","path":"../../test262/test/built-ins/Array/prototype/includes/return-abrupt-tointeger-fromindex.js"}